### ISSUE TITLE
Android - initialDate argument error (Ljava/util/Calendar)

### ISSUE THREAD

**Issue by bradmartin** [AntonioCuevaUrraco/nativescript-timedatepicker#1]
When passing a .js date in the initialDate argument for Android the following error is returned:

       Error: Cannot convert object to Ljava/util/Calendar; at index 1

and the stacktrace leads to the timedatepicker-handler.js file line 10, column 73.

I've tried a manipulated date with the following:

         var date = new Date();
         var yearMinus17 = date.getFullYear() - 17;
         var initialDate = new Date(yearMinus17, currentMonth, currentDay);
         //Initialize the PickerManager (.init(yourCallback, title, initialDate))
         PickerManager.init(mCallback, null, initialDate);

I've also tried just a new Date() but same result. I might have an invalid date being passed so an example would be nice if what I'm doing is wrong.

**Comment by AntonioCuevaUrraco** [comment]
Nothing wrong with your date, there was a bug in the plugin.
Fix in V0.1.1

also remember when using it that month 11 is December :-)

**Comment by bradmartin** [comment]
Great, thanks. Oh yea I forgot the month - 1 and had to go back to mdn for the doc :) I'll try it out tomorrow and close this out.

**Comment by bradmartin** [comment]
@AntonioCuevaUrraco - tried it out and now the date defaults correctly. However, I think it's caused another issue.

I used the same code as I originally posted, it works then when clicking 'DONE' to return the date in the callback:

      NullPointerException: Attempt to invoke virtual method 'void java.util.Calendar.set(int, int, int);     on a null object reference at 
       com.android.datetimepicker.PickerManager.onDateSet(PickerManager.java:127)

**Comment by AntonioCuevaUrraco** [comment]
@bradmartin my bad, I forgot to put the new .aar library in the plugin I published :-(

I made the change and test that is working with the published npm

**Comment by bradmartin** [comment]
Thanks!
