### ISSUE TITLE
Localization / Translation

### ISSUE THREAD

**Issue by huehnerhose** [AntonioCuevaUrraco/nativescript-timedatepicker#11]
Hi,

under iOS the "done" and "cancel" "Buttons" don't get translated according to my system language. Android changes to my language setting (german). 
I am afraid you are using the system "done"-Icon under iOS? I do not understand why, but the "done"-ICON seems to be the word "done" (i've seen that with the action bar too). Thanks Jony Ive... 

Is there / where is the place to set what button will be displayed there? At the moment I really just need german translation :D 

Thanks

**Comment by AntonioCuevaUrraco** [comment]
As the original library for iOS didn't have a localization option (when I put this together I haven't check it out since then) I made a patch to make it work and hosted it separately.

Anyway, for ios you can see on the code that the init method has optional parameters:
```ts
init(mCallback: any, title?: any, initialDate?: any, doneText?: any, cancelText?: any, buttonColor?: any)

```

use them to put german or whatever you want. Personally I use nothing as cancel text and "Ok" as done text and so far seams everybody understand it :-D

**Comment by huehnerhose** [comment]
perfect thanks!

**Comment by huehnerhose** [comment]
Sorry to reopen this, but i ran into a problem, especially with iOS10. 

The "button"-area seams to be very small. With the default "buttons" (Done/Cancel) the tapable area is bigger. 

I looked into the used pod and hoped to understand a think... well not the case ;) But I noticed:
https://github.com/hackiftekhar/IQActionSheetPickerView/pull/20
The original pod added the button feature.

So here are two questions:
1. Is there a simple way to get "bigger" tab-areas?
2. May the update on the pod, together with the included further updates, fixes these issues?

Thanks!

**Comment by AntonioCuevaUrraco** [comment]
@huehnerhose yes, I think is better to use the original pod, I made a "dirty patch" to get working the needed things. I will have a look as soon as I have time but I am really busy and may pass some time. If you need it really soon make some test yourself, just change the pod file inside ios platform to point to the original pod and modify a couple of methods to set the color and text of the buttons using the actual code as an example of calling the ios library (is easier than it looks like)
