### ISSUE TITLE
Update underlying iOS Library for iOS 10

### ISSUE THREAD

**Issue by creambyemute** [AntonioCuevaUrraco/nativescript-timedatepicker#15]
Hey, 

I've experienced some layouting problems on iOS with the library: Close/Done button are a bit cut off as they start offscreen.

I think the problem is also described here and a fix was already realsed: https://github.com/hackiftekhar/IQActionSheetPickerView/issues/21

Would you mind having a look at it and maybe update the library?

Cheers,

**Comment by AntonioCuevaUrraco** [comment]
It have been requested by several guys and yes, I want to update the iOS lib but again I have no time right

**Comment by DomGaud** [comment]
Hi @AntonioCuevaUrraco, I know you struggling to find time, but updating the library to fix this issue will be really appreciated.

Thanks in advance,

**Comment by DomGaud** [comment]
Hi @AntonioCuevaUrraco, I have sent you a pull request with fix.

**Comment by AntonioCuevaUrraco** [comment]
done bb48b01647dd12fa716c6530af8be5c146bc9ce8
