### ISSUE TITLE
TypeError: mPickerManager.minimumDate is not a function

### ISSUE THREAD

**Issue by Daxito** [AntonioCuevaUrraco/nativescript-timedatepicker#16]
Hi, 
I am getting this error with the version 1.0.0 for iOS

file:///app/tns_modules/nativescript-timedatepicker/timedatepicker-handler.js:113:35: JS ERROR TypeError: mPickerManager.minimumDate is not a function. (In 'mPickerManager.minimumDate(_toNativeDate(date))', 'mPickerManager.minimumDate' is null)

Before this error I saw a warning 
CONSOLE WARN file:///app/tns_modules/nativescript-timedatepicker/timedatepicker-handler.js:7:14: Objective-C class name "MyDelegate" is already in use - using "MyDelegate1" instead.

NS 2.3, xcode 7.3.1

**Comment by AntonioCuevaUrraco** [comment]
Yes, now it is fixed on bb48b01647dd12fa716c6530af8be5c146bc9ce8
