### ISSUE TITLE
How to change the returned result to date in javascript

### ISSUE THREAD

**Issue by andycwwai** [AntonioCuevaUrraco/nativescript-timedatepicker#2]
I can successfully use the picker in Android and my callback is being called. However, I found that the returned result is a string. How can I change the string back to a date object? Thanks.

**Comment by AntonioCuevaUrraco** [comment]
I am using moment.js to manage all the time related business.
```ts
 var mSuccessTimeCallback = function(result) {
      if (result) {
        var scheduleMoment = moment(result);
        var scheduleJS = scheduleMoment.toDate();
      }
    };
 But I am thinking to update the plugin soon because the returned string is giving some problems with localization and the method will be like this. 
```ts
 var mSuccessTimeCallback = function(result) {
      if (result) {
        var scheduleDate = moment(result, "DD MM YYYY HH:mm z");
        var scheduleJS = scheduleMoment.toDate();
      }
    };

Just keep in contact if you have problems and we will solve them :-)

**Comment by andycwwai** [comment]
Thanks for your reply. I would like to know if the format of the returned string is consistent no matter what the device is or what the locale of the client is? Meanwhile, I'm using moment(result, "ddd, DD MMM YYYY HH:mm:ss GMTZ") to get the timestamp. What do you think? Thanks.

**Comment by AntonioCuevaUrraco** [comment]
That's the thing, I found that depending on the locale the return string will have the day in a different language and moment get confused. I tested with a different format returned by the plugin  "DD MM YYYY HH:mm z" and it have been working with no problem. I will update as soon as possible the libraries on the plugin

**Comment by AntonioCuevaUrraco** [comment]
@andycwwai updated to 0.2.0 with format  "DD MM YYYY HH:mm z"
It should not cause problem with localization and neither moment.js should complain, also you can set on iOS the text for apply, cancel and the color of the text

**Comment by andycwwai** [comment]
Thanks!!

**Comment by emmanuel128** [comment]
Hi, I need to format the string to: `YYYY-MM-DDTHH:mm:ss`. Any ideas?
