### ISSUE TITLE
Wrong year appearing on timedatepicker

### ISSUE THREAD

**Issue by rjayako** [AntonioCuevaUrraco/nativescript-timedatepicker#22]
Looks like `PickerManager.init(mCallback, null, new Date());` is displaying 2016 year and not 2017

Any ideas?

**Comment by AntonioCuevaUrraco** [comment]
maybe related to? https://github.com/AntonioCuevaUrraco/nativescript-timedatepicker/issues/25

**Comment by AntonioCuevaUrraco** [comment]
Inactivity
