### ISSUE TITLE
Return date not as string but a normal date type?

### ISSUE THREAD

**Issue by rjayako** [AntonioCuevaUrraco/nativescript-timedatepicker#23]
Hey wondering why the return date on the callback is not a normal Date type but instead a string that looks like this `18 12 2016 20:43 -0500` is it possible to return this as normal Date type?

**Comment by rjayako** [comment]
Found a workaround for this in the closed issues sections.

**Comment by pasaneramusugoda** [comment]
@rjayako I'm facing the same problem. May I know what your workaround for this?
Thanks in advance.

**Comment by cagatayoncul** [comment]
Can you share us solution?

**Comment by pasaneramusugoda** [comment]
@cagatayoncul this might not be the perfect solution. But this is working.

[https://gist.github.com/pasaneramusugoda/42c1b981da501fca66dadf610e0999eb](url)
