### ISSUE TITLE
Zero based months

### ISSUE THREAD

**Issue by vincentduprez** [AntonioCuevaUrraco/nativescript-timedatepicker#25]
Hi,

ToNativeDate does not take into consideration that a JS date object has months in 0 based index (January = 0, february = 1) and thus converts the month 1 to january instead of february.
I need to increment//offset the initial date by 1 month to have it displaying the right date.

Fortunately the ios date object understands that 0 of year 2018 is ouside its bounds and ceonverts it to month 12 (december) of 2017 of the previous year.

**Comment by vincentduprez** [comment]
... but it's a dirty hack

**Comment by AntonioCuevaUrraco** [comment]
https://github.com/AntonioCuevaUrraco/nativescript-timedatepicker/pull/28
