### ISSUE TITLE
Bound widgets (Label/TextField) doesn't update value (on UI) after setting on picker selection

### ISSUE THREAD

**Issue by YeshanJay** [AntonioCuevaUrraco/nativescript-timedatepicker#27]
Hi,
I'm having difficulty trying to bind the selected date on to a label. It doesn't seem to update even though it has the right value. 
However it will update only if there is a major change in the user interface, e.g.: opening the picker again or toggling show/hide on another layout on the same page.

Here is how the html looks like..
```html
<StackLayout>
    <Label text="Date" horizontalAlignment="left"></Label>
    <GridLayout rows="auto" columns="*, 110">
        <Label col="0" [text]="myDate | date: 'dd MMM EEE, yyyy'" horizontalAlignment="left"></Label>
        <Label col="1" text="&#xf073; Change Date" class="fa-icon" (tap)="changeDate()" horizontalAlignment="center" verticalAlignment="center"></Label>
    </GridLayout>
</StackLayout>
```

Typescript code as below...
```javascript
@Component({ ... })
export class MyPage {
    myDate: Date = new Date();

    changeDate(): void {
        TimeDatePicker.init((result) => {
            // Date.parse is from the [DateJS](http://www.datejs.com) plugin.
            let milli = Date.parse(result);
            this.myDate = new Date(milli);
        }, undefined, this.myDate);

        TimeDatePicker.showDatePickerDialog();
    }
}
```

Have any idea what the problem is?
Thanks in advance.

**Comment by BryanYomar** [comment]
Same problem here.

**Comment by rajasekarsp** [comment]
Same here. Any Fix?

**Comment by BryanYomar** [comment]
I found a workaround, there's no fix on the plugin as far as I know.

You can import ChangeDetectorRef to the project and call it whenever you need real time checking on value changes.

Here's some code snippets to help:

`import { ChangeDetectorRef } from "@angular/core";`

`constructor(private cdr: ChangeDetectorRef) { } `

After that, wherever you want to check for a change add the following line: `this.cdr.detectChanges();`

Hope this helps!

**Comment by rajasekarsp** [comment]
Thank you so much @BryanYomar . It Works!.

Still we would like straightforward fix.

**Comment by BryanYomar** [comment]
Sure! Glad it did.

I'd like the fix too, hope it gets done.
