### ISSUE TITLE
Installing dependency for ios is failed

### ISSUE THREAD

**Issue by patuku-roy** [AntonioCuevaUrraco/nativescript-timedatepicker#3]
When I'm trying to `tns run ios` the dependency has a problem, because the podspec doesn't valid.

```
Installing pods...
Analyzing dependencies
Pre-downloading: `IQActionSheetPickerView` from `https://github.com/Smarp/NativescriptIQActionSheetPickerView`
[!] The `IQActionSheetPickerView` pod failed to validate due to 3 errors:
    - ERROR | attributes: Missing required attribute `authors`.
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `source`.
```

Related issues [here](https://github.com/hackiftekhar/IQActionSheetPickerView/issues/8) and suggested to use podfile like this:

```
pod 'IQActionSheetPickerView'
```

instead of

```
pod 'IQActionSheetPickerView', :git => 'https://github.com/Smarp/NativescriptIQActionSheetPickerView'
```

I changed my local podfile and work like a charm.

**Comment by AntonioCuevaUrraco** [comment]
Thank you for informing,

I will be working on fix it as soon as possible. 

The problem with using the source code on https://github.com/hackiftekhar/IQActionSheetPickerView instead of https://github.com/Smarp/NativescriptIQActionSheetPickerView is that on the original there is no functionality to change the text or color of the buttons (at least there was no on the moment I put this together)

**Comment by patuku-roy** [comment]
I'm using NS 2.0.1 and you are right, when I installed using:

```
pod 'IQActionSheetPickerView'
```

I can passed the installation but I can't show the picker and this is the error:

```
JS ERROR TypeError: IQActionSheetPickerView.alloc().initWithTitleDoneTextCancelTextDelegate is not a function. (In 'IQActionSheetPickerView.alloc().initWithTitleDoneTextCancelTextDelegate(_title, _doneText, _cancelText, _delegate)', 'IQActionSheetPickerView.alloc().initWithTitleDoneTextCancelTextDelegate' is undefined)
```

I'll try to switch back to repository or maybe the earlier tag release.

**Comment by patuku-roy** [comment]
I saw you're just updating the repository and I try to reinstall the plugin. And new warning appear when I installing:

```
Unable to find a specification for 'IQActionSheetPickerView'.
```

Can you give me a direction how to install this plugin correctly?

**Comment by AntonioCuevaUrraco** [comment]
@patuku-roy I have been changing the podspec to make it work, and it is working for me now, just remove the plugin and add it again and it should be working good. Tell me if you have some problem still and we can check it out. But hopefully is done...there is just too many gits pointing to to many other gits ;-)

**Comment by patuku-roy** [comment]
@AntonioCuevaUrraco Cool ... working beautifully ... thanks for your quick response, I really appreciated.
