### ISSUE TITLE
How to use with Angular ?

### ISSUE THREAD

**Issue by msarsha** [AntonioCuevaUrraco/nativescript-timedatepicker#30]

**Comment by NathanWalker** [comment]
Just as the docs in the readme state. init it in a component constructor or ngOnInit `TimeDatePicker.init(this._mCallback.bind(this), null, new Date());` and then bind to a method that would open it: 
```
public openPicker() {
        TimeDatePicker.showDatePickerDialog();
    }
```

@AntonioCuevaUrraco i would close this issue.
