### ISSUE TITLE
Plugin break with Angular 2 with Webpacking?

### ISSUE THREAD

**Issue by dlucidone** [AntonioCuevaUrraco/nativescript-timedatepicker#31]
It works normally without webpacking in Angular but as soon as i tried to webpack it. The build is crashing? Any help

**Comment by manojdcoder** [comment]
I'm facing the same issue, web pack with Android works but iOS is crashing with errors below.

```
objc[22153]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11ae48998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11ac6a880). One of the two will be used. Which one is undefined.
1   0x1010ad29c -[TNSRuntime executeModule:referredBy:]
2   0x100b33e10 main
3   0x10603568d start
4   0x1
file:///app/bundle.js:69514:29: JS ERROR TypeError: Attempted to assign to readonly property.
Jun  6 18:31:11 Manojkumars-MacBook-Pro com.apple.CoreSimulator.SimDevice.F2029514-A16E-4A95-B17D-AC11B2BB0278.launchd_sim[5064] (UIKitApplication:com.myapp.app[0xebdb][22153]): Service exited due to Segmentation fault: 11
```

**Comment by dlucidone** [comment]
@manojdcoder  Any Help on this?

**Comment by NathanWalker** [comment]
@AntonioCuevaUrraco I have found this plugin to work just fine with Angular and webpack - sounds like above issue is not related to this plugin. I would close this.

**Comment by dlucidone** [comment]
@NathanWalker Can you some code so that It could help us too.

**Comment by NathanWalker** [comment]
Exactly what's in the readme.

**Comment by AntonioCuevaUrraco** [comment]
Thank you @NathanWalker
@dlucidone give it a try in a new clean project and see if it related to:
- this plug in in particular
- all the plugins that use cocoa
- your local set up

**Comment by manojdcoder** [comment]
@AntonioCuevaUrraco I confirm the plugin works just fine. You may close this issue. 

Thanks for the support @NathanWalker & @AntonioCuevaUrraco

**Comment by manojdcoder** [comment]
In my case the actual issue was with `noEmitHelpers` flag - [NativeScript/nativescript-dev-webpack/issues/70](NativeScript/nativescript-dev-webpack/issues/70#issuecomment-279085077).  Hope this might help someone.

**Comment by dlucidone** [comment]
@manojdcoder You have explicitly added this flag?

**Comment by dlucidone** [comment]
@manojdcoder how did you figured that out?

**Comment by dlucidone** [comment]
@AntonioCuevaUrraco  @manojdcoder I get the below error with webpack

`2017-11-21 16:42:00.024299+0530 PulseIOSAdvance[18897:115460] file:///app/bundle.js:116705:40: JS ERROR ReferenceError: Can't find variable: applicationModule`

It is working fine without webpack bundle.Any Help!
