### ISSUE TITLE
Translate Guide Request

### ISSUE THREAD

**Issue by isaacfi** [AntonioCuevaUrraco/nativescript-timedatepicker#33]
Can you include much more documentation to translate this plugin? To iOS and Android please.

Regards.

**Comment by AntonioCuevaUrraco** [comment]
@isaacfi change the language of the phone and the buttons will change also, iOS and Android.   

For more documentation of supported languages you can look at the core libs.

For iOS https://github.com/hackiftekhar/IQActionSheetPickerView
For Android https://github.com/CiTuX/datetimepicker
