### ISSUE TITLE
How to get local calendar?

### ISSUE THREAD

**Issue by nrbn** [AntonioCuevaUrraco/nativescript-timedatepicker#36]
Hi,

This great calendar, i like it. I want to change language of calendar, is it possible. Nativescript just adds attribute (`locale="nb-NO"`) to calendar tag like this:

`
<calendar:RadCalendar id="calendar" locale="nb-NO" dateSelected="onDateSelected" dateDeselected="onDateDeselected" selectionMode="Multiple"/>`

How can i do this in your plugin?

Regards
Rubi

**Comment by AntonioCuevaUrraco** [comment]
Readme explain localization for iOS. After adding a supported language the calendar will use the device language.
For android is using the device language by default
https://github.com/AntonioCuevaUrraco/nativescript-timedatepicker
