### ISSUE TITLE
Convert the date string in the callback to a date

### ISSUE THREAD

**Issue by RaphaelJenni** [AntonioCuevaUrraco/nativescript-timedatepicker#37]
Please convert the date string (`25 10 2017 08:00 -0400` `ddmmyy`) to a date (`10 25 2017 08:00 -0400` `mmddyy`). At the moment the app crashes because it can't convert the string to a date.

**Comment by RaphaelJenni** [comment]
This conversation works:
```
const dateParts = result.split(' ');
new Date(`${dateParts[1]}/${dateParts[0]}/${dateParts[2]} ${dateParts[3]} ${dateParts[4]}`);
```

It's very hacky, hoping for a better solution.

**Comment by AntonioCuevaUrraco** [comment]
@RaphaelJenni date conversion is kind of complicate business that lead to a lot of errors. And I don't want to overcomplicate this library.

Personally I use moment.js to deal with the dates on my projects.
https://github.com/AntonioCuevaUrraco/nativescript-timedatepicker/issues/2
