### ISSUE TITLE
Plugin breaks Android build

### ISSUE THREAD

**Issue by dkast** [AntonioCuevaUrraco/nativescript-timedatepicker#39]
After installing the plugin in your project if you try to build or run an app with `tns run android` the script fails with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'drawerapp'.
> Could not resolve all dependencies for configuration ':_F0F1F2DebugApkCopy'.
   > Could not find :nativescript-datetimepicker-release:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
```

We use the plugin in one of our projects and until last week everything was working fine. When we try to do a new build this week this error was thrown. We are using version 1.2.0. Everything works fine on iOS.

**How to reproduce**
Create a new project and add the plugin. Try to run on android.

**Comment by AntonioCuevaUrraco** [comment]
@dkast Which version of NS client, core, and android are you using?

**Comment by dkast** [comment]
Hi @AntonioCuevaUrraco, we are using the nativescript cli ver 3.3.0 and tns-core-modules 3.1.0. We are using Android SDK api 23 (6.0). We also tried with tns-core-modules 3.3.0 with the same effect.

Here is our package.json
```
"nativescript": {
    "id": "com.app.indicadores",
    "tns-android": {
      "version": "3.3.0"
    },
    "tns-ios": {
      "version": "3.3.0"
    }
  },
  "dependencies": {
    "everlive-sdk": "^1.9.4",
    "moment": "^2.18.1",
    "nativescript-appversion": "^1.4.1",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-platform": "1.1.1",
    "nativescript-platform-css": "^1.5.0",
    "nativescript-pro-ui": "^3.1.3",
    "nativescript-pulltorefresh": "^2.0.1",
    "nativescript-push-notifications": "^0.1.5",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-timedatepicker": "^1.2.0",
    "tns-core-modules": "3.1.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }
}
```

Thanks!

**Comment by jevenson** [comment]
I think the culprit is tns-android 3.3.0. Using 3.2.0 works for me, but I get this same error when using 3.3.0

**Comment by danielgek** [comment]
just made a pr to fix this

**Comment by danielgek** [comment]
just move the aar file out of the libs folder and you are good to go
