### ISSUE TITLE
Displaying just a year picker. 

### ISSUE THREAD

**Issue by spstratis** [AntonioCuevaUrraco/nativescript-timedatepicker#4]
Hi there, great work with this plugin! I have a question though, is it possible to display a year picker and then the day, month picker?

**Comment by AntonioCuevaUrraco** [comment]
Sorry for the delay, I was on holidays.

The 5 screenshots that you see on the readme are the only things implemented by now. A year picker is not included.

For ios it can be added using https://github.com/hackiftekhar/IQActionSheetPickerView/blob/master/IQActionSheetPickerView/IQActionSheetPickerView.h
IQActionSheetPickerStyleTextPicker and pass the a list of numbers for the years 1990, 1991, 1992...

For the android side more work is required... I will try to work on this as soon as I have time

**Comment by hvadotnarola** [comment]
@AntonioCuevaUrraco can you please suggest how can i give date/time picker initial date or what format that requires ?
