### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by code-surf-er** [AntonioCuevaUrraco/nativescript-timedatepicker#6]
disclaimer: I am from the Microsoft world and an absolute noob to the world of open source. but it is never too late :)

I am getting the error, here is what I am doing.

1) Created a native script tns create test-app 
2) Ran it to verify everything is working ( The default tap app)
3) ran npm i nativescript-drop-down from the app directory terminal window
4) Ran the app again using tns run ios --emulator

Processing node_modules failed. Error: Command sandbox-pod failed with exit code 71 Error output: 
 sandbox-exec: /Users/[user]/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod: Operation not permitted

Am I missing something ?

Thanks

**Comment by AntonioCuevaUrraco** [comment]
Sure is never too late to apply your skills somewhere else : -) 
In your steps I don't see when you do the tns plugin add nativescript-timedatepicker. Also no idea about the npm drop-down thing.  The error is a general set up problem where your system doesn't have cocoa pods (IOS library repository ) ready for NS. https://github.com/NativeScript/nativescript-cli/issues/1249

**Comment by code-surf-er** [comment]
apologies for the typo.  #3) is actually "npm i nativescript-timedatepicker" instead of "npm i nativescript-drop-down ".

I verified again. A new app is working fine. but as soon as I run "npm i nativescript-timedatepicker"  OR "tns plugin add nativescript-timedatepicker" i get the error when I run the app (tns run ios --emulator). So something is happening after i install the plugin.

**Comment by AntonioCuevaUrraco** [comment]
Before you install the plugin you have no dependencies to any cocoa, after you install the this plugin (or almost any other) you have. The tns client is setting up your project to use cocoa and is failing. Check the link of my previous answer

**Comment by code-surf-er** [comment]
oh ok.. i understand the connection now.. I followed the instruction from the link you mentioned and now it is working fine. I also did tns build ios which i hadn't done earlier, i was on livesync. That could also be one of the issues. 

But it is working fine now. Thank you so much
