### ISSUE TITLE
TypeError: Cannot read property 'PickerManager' of undefined

### ISSUE THREAD

**Issue by blaur** [AntonioCuevaUrraco/nativescript-timedatepicker#8]
I am getting the following error when trying to load the standard sample: 

```
com.tns.NativeScriptException: 
Calling js method onClick failed

EXCEPTION: Error in pages/appointment/startdate/startdate.html:50:16
ORIGINAL EXCEPTION: TypeError: Cannot read property 'PickerManager' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'PickerManager' of undefined
    at Object.init (/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-timedatepicker/timedatepicker-handler.js:10:56)
    at StartDate.newAppointment (/data/data/org.nativescript.groceries/files/app/pages/appointment/startdate/startdate.component.js:116:27)
    at DebugAppView._View_StartDate0._handle_tap_35_0 (StartDate.template.js:283:28)
    at /data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:375:24
    at /data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-angular/renderer.js:204:26
    at ZoneDelegate.invoke (/data/data/org.nativescript.groceries/files/app/tns_modules/zone.js/dist/zone-node.js:281:29)
    at Object.NgZoneImp
```

So com.android.datetimepicker does not exist. 

Any ideas?

**Comment by AntonioCuevaUrraco** [comment]
Which version on NS (client, core_modules and android platform) are you running? Also that error means that the native library was not added to the platform. You can remove the plugin and then add again to see if you get when you do tns run android
```
Successfully prepared plugin nativescript-timedatepicker for android.
```
You can also remove and add again the platform.

**Comment by AntonioCuevaUrraco** [comment]
close due to inactivity

**Comment by Zyzle** [comment]
I hate to re-open an old issue but I was having the same problem and found the solution. It seems that running `tns livesync` rather than `tsn run` after installing the plugin causes this error when you attempt to load an application with the timedatepicker control. After the first `tns run` the `livesync` command will work again.

**Comment by AntonioCuevaUrraco** [comment]
Yes that will happen with all the plugins because livesync does not check if you put/modify the plugins and only will move the new js files from app to platform folder
