### ISSUE TITLE
Fix __extends on webpack bundle issue

### ISSUE THREAD

**Issue by leocaseiro** [AntonioCuevaUrraco/nativescript-timedatepicker#9]
Hi @AntonioCuevaUrraco,

Thanks for this amazing plugin.

I was wondering how do you publish from .ts to .js.
Do you have a .tsconfig.json file?

I'd like to add the parameter noEmitHelpers, so we [can bundle with webpack](https://github.com/NativeScript/nativescript-dev-webpack/issues/8#issuecomment-233526850): 
```
"noEmitHelpers": true
```

**Comment by AntonioCuevaUrraco** [comment]
Thank you. I put a tsconfig.json, feel free to check with webpack and make a pull request :-)
